apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edu-ml
resources:
  - ../../../../deploy/k8s/manifests/namespace.yaml
  - ../../../../deploy/k8s/manifests/redis-analyze.yaml
  - ../../../../deploy/k8s/manifests/redis-generate.yaml
  - ../../../../deploy/k8s/manifests/code-analyze.yaml
  - ../../../../deploy/k8s/manifests/task-generate.yaml
  - ../../../../deploy/k8s/manifests/ml-balancer-deployment.yaml
  - ../../../../deploy/k8s/manifests/ml-balancer-service.yaml
  - ../../../../deploy/k8s/manifests/network-policy-ml-tier.yaml
patches:
  - path: ../../../../deploy/k8s/clusters/ml/namespace-labels.yaml
configMapGenerator:
  - name: ml-balancer-nginx-conf
    files:
      - default.conf=../../../../deploy/k8s/manifests/files/ml-balancer.conf
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: edu-ml-code-analyze
    newName: edu-ml-code-analyze
    newTag: latest
  - name: edu-ml-task-generate
    newName: edu-ml-task-generate
    newTag: latest
