apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-mock
spec:
  template:
    spec:
      containers:
        - name: worker
          volumeMounts:
            - name: mock-script
              $patch: delete
          env:
            - name: REDIS_URL
              value: "rediss://redis:6379/0?ssl_cert_reqs=required&ssl_check_hostname=false&ssl_ca_certs=/etc/edu-ml/redis-tls/ca.crt&ssl_certfile=/etc/edu-ml/redis-client-tls/tls.crt&ssl_keyfile=/etc/edu-ml/redis-client-tls/tls.key"
            - name: POSTGRES_SSL_CHECK_HOSTNAME
              value: "false"
