apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edu-ml
resources:
  - ../../manifests/namespace.yaml
  - ../../manifests/auth-service.yaml
  - ../../manifests/gateway-deployment.yaml
  - ../../manifests/gateway-service.yaml
  - edge-balancer-deployment.yaml
  - edge-balancer-service.yaml
  - ingress.yaml
  - ml-balancer-externalname.yaml
configMapGenerator:
  - name: gateway-nginx-conf
    files:
      - default.conf=../../manifests/files/default.conf
  - name: edge-balancer-nginx-conf
    files:
      - default.conf=files/edge-balancer.conf
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: edu-ml-auth-service
    newName: edu-ml-auth-service
    newTag: latest