apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edu-ml
resources:
  - ../../manifests/namespace.yaml
  - ../../manifests/gateway-deployment.yaml
  - ../../manifests/gateway-service.yaml
  - edge-balancer-deployment.yaml
  - edge-balancer-service.yaml
  - ingress.yaml
  - redis-externalname.yaml
  - postgres-externalname.yaml
configMapGenerator:
  - name: edge-balancer-nginx-conf
    files:
      - default.conf=files/edge-balancer.conf
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: api-request-gateway
    newName: ghcr.io/yund3r/rest-service
    newTag: latest