apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-analyze
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-generate
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-pipeline
spec:
  replicas: 0
