apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-balancer
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: edu-ml.io/tier
                    operator: In
                    values:
                      - gpu
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
