apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edu-ml
resources:
  - ../../../clusters/edge
patches:
  - path: patches/gateway-deployment.yaml
  - path: patches/ml-balancer-externalname.yaml
configMapGenerator:
  - name: gateway-nginx-conf
    behavior: replace
    files:
      - default.conf=files/default.conf
      - ml_tls.inc=files/ml_tls.inc
generatorOptions:
  disableNameSuffixHash: true
