apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../clusters/ml
patches:
  - path: ../patches/code-analyze-gpu.yaml
  - path: ../patches/task-generate-gpu.yaml
  - path: ../patches/worker-pipeline-gpu.yaml
