apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edu-ml
resources:
  - ../../manifests/namespace.yaml
  - ../../manifests/redis.yaml
  - ../../manifests/postgres.yaml
  - ../../manifests/network-policy-data-tier.yaml
  - ../../manifests/worker-analyze.yaml
  - ../../manifests/worker-generate.yaml
  - ../../manifests/worker-pipeline.yaml
patches:
  - path: namespace-labels.yaml
configMapGenerator:
  - name: postgres-schema
    files:
      - 001_schema.sql=../../../../api-request-gateway/db/migrations/001_schema.sql
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: api-request-gateway
    newName: ghcr.io/yund3r/rest-service
    newTag: latest
