apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edu-ml
resources:
  - ../../manifests/namespace.yaml
  - ../../manifests/redis-analyze.yaml
  - ../../manifests/redis-generate.yaml
  - ../../manifests/code-analyze.yaml
  - ../../manifests/task-generate.yaml
  - ../../manifests/ml-balancer-deployment.yaml
  - ../../manifests/ml-balancer-service.yaml
  - ../../manifests/network-policy-ml-tier.yaml
patches:
  - path: namespace-labels.yaml
configMapGenerator:
  - name: ml-balancer-nginx-conf
    files:
      - default.conf=../../manifests/files/ml-balancer.conf
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: edu-ml-code-analyze
    newName: edu-ml-code-analyze
    newTag: latest
  - name: edu-ml-task-generate
    newName: edu-ml-task-generate
    newTag: latest
